name: TSSC SBOM Sample Github Workflow

on:
  push:
    branches: ["**"]

jobs:
  ci:
    name: Run CI
    runs-on: ubuntu-latest

    steps:
      - name: Grab SBOM sample
        run: |
          curl https://raw.githubusercontent.com/redhat-appstudio/tssc-sample-sbom-scans/refs/heads/main/live-demo
